//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _08___Calculadora_Web_Service.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        _08___Calculadora_Web_Service.ServiceReference1.HelloWorldResponse HelloWorld(_08___Calculadora_Web_Service.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<_08___Calculadora_Web_Service.ServiceReference1.HelloWorldResponse> HelloWorldAsync(_08___Calculadora_Web_Service.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento elementos del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularInfija", ReplyAction="*")]
        _08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaResponse CalcularInfija(_08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularInfija", ReplyAction="*")]
        System.Threading.Tasks.Task<_08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaResponse> CalcularInfijaAsync(_08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento elementos del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularPostfija", ReplyAction="*")]
        _08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaResponse CalcularPostfija(_08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularPostfija", ReplyAction="*")]
        System.Threading.Tasks.Task<_08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaResponse> CalcularPostfijaAsync(_08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento elementos del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularPrefija", ReplyAction="*")]
        _08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaResponse CalcularPrefija(_08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularPrefija", ReplyAction="*")]
        System.Threading.Tasks.Task<_08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaResponse> CalcularPrefijaAsync(_08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public _08___Calculadora_Web_Service.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(_08___Calculadora_Web_Service.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public _08___Calculadora_Web_Service.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(_08___Calculadora_Web_Service.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularInfijaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularInfija", Namespace="http://tempuri.org/", Order=0)]
        public _08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaRequestBody Body;
        
        public CalcularInfijaRequest() {
        }
        
        public CalcularInfijaRequest(_08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularInfijaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _08___Calculadora_Web_Service.ServiceReference1.ArrayOfString elementos;
        
        public CalcularInfijaRequestBody() {
        }
        
        public CalcularInfijaRequestBody(_08___Calculadora_Web_Service.ServiceReference1.ArrayOfString elementos) {
            this.elementos = elementos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularInfijaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularInfijaResponse", Namespace="http://tempuri.org/", Order=0)]
        public _08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaResponseBody Body;
        
        public CalcularInfijaResponse() {
        }
        
        public CalcularInfijaResponse(_08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularInfijaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalcularInfijaResult;
        
        public CalcularInfijaResponseBody() {
        }
        
        public CalcularInfijaResponseBody(string CalcularInfijaResult) {
            this.CalcularInfijaResult = CalcularInfijaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularPostfijaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularPostfija", Namespace="http://tempuri.org/", Order=0)]
        public _08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaRequestBody Body;
        
        public CalcularPostfijaRequest() {
        }
        
        public CalcularPostfijaRequest(_08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularPostfijaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _08___Calculadora_Web_Service.ServiceReference1.ArrayOfString elementos;
        
        public CalcularPostfijaRequestBody() {
        }
        
        public CalcularPostfijaRequestBody(_08___Calculadora_Web_Service.ServiceReference1.ArrayOfString elementos) {
            this.elementos = elementos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularPostfijaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularPostfijaResponse", Namespace="http://tempuri.org/", Order=0)]
        public _08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaResponseBody Body;
        
        public CalcularPostfijaResponse() {
        }
        
        public CalcularPostfijaResponse(_08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularPostfijaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalcularPostfijaResult;
        
        public CalcularPostfijaResponseBody() {
        }
        
        public CalcularPostfijaResponseBody(string CalcularPostfijaResult) {
            this.CalcularPostfijaResult = CalcularPostfijaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularPrefijaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularPrefija", Namespace="http://tempuri.org/", Order=0)]
        public _08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaRequestBody Body;
        
        public CalcularPrefijaRequest() {
        }
        
        public CalcularPrefijaRequest(_08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularPrefijaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _08___Calculadora_Web_Service.ServiceReference1.ArrayOfString elementos;
        
        public CalcularPrefijaRequestBody() {
        }
        
        public CalcularPrefijaRequestBody(_08___Calculadora_Web_Service.ServiceReference1.ArrayOfString elementos) {
            this.elementos = elementos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularPrefijaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularPrefijaResponse", Namespace="http://tempuri.org/", Order=0)]
        public _08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaResponseBody Body;
        
        public CalcularPrefijaResponse() {
        }
        
        public CalcularPrefijaResponse(_08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularPrefijaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalcularPrefijaResult;
        
        public CalcularPrefijaResponseBody() {
        }
        
        public CalcularPrefijaResponseBody(string CalcularPrefijaResult) {
            this.CalcularPrefijaResult = CalcularPrefijaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : _08___Calculadora_Web_Service.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<_08___Calculadora_Web_Service.ServiceReference1.WebService1Soap>, _08___Calculadora_Web_Service.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _08___Calculadora_Web_Service.ServiceReference1.HelloWorldResponse _08___Calculadora_Web_Service.ServiceReference1.WebService1Soap.HelloWorld(_08___Calculadora_Web_Service.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            _08___Calculadora_Web_Service.ServiceReference1.HelloWorldRequest inValue = new _08___Calculadora_Web_Service.ServiceReference1.HelloWorldRequest();
            inValue.Body = new _08___Calculadora_Web_Service.ServiceReference1.HelloWorldRequestBody();
            _08___Calculadora_Web_Service.ServiceReference1.HelloWorldResponse retVal = ((_08___Calculadora_Web_Service.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_08___Calculadora_Web_Service.ServiceReference1.HelloWorldResponse> _08___Calculadora_Web_Service.ServiceReference1.WebService1Soap.HelloWorldAsync(_08___Calculadora_Web_Service.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<_08___Calculadora_Web_Service.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            _08___Calculadora_Web_Service.ServiceReference1.HelloWorldRequest inValue = new _08___Calculadora_Web_Service.ServiceReference1.HelloWorldRequest();
            inValue.Body = new _08___Calculadora_Web_Service.ServiceReference1.HelloWorldRequestBody();
            return ((_08___Calculadora_Web_Service.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaResponse _08___Calculadora_Web_Service.ServiceReference1.WebService1Soap.CalcularInfija(_08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaRequest request) {
            return base.Channel.CalcularInfija(request);
        }
        
        public string CalcularInfija(_08___Calculadora_Web_Service.ServiceReference1.ArrayOfString elementos) {
            _08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaRequest inValue = new _08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaRequest();
            inValue.Body = new _08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaRequestBody();
            inValue.Body.elementos = elementos;
            _08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaResponse retVal = ((_08___Calculadora_Web_Service.ServiceReference1.WebService1Soap)(this)).CalcularInfija(inValue);
            return retVal.Body.CalcularInfijaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaResponse> _08___Calculadora_Web_Service.ServiceReference1.WebService1Soap.CalcularInfijaAsync(_08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaRequest request) {
            return base.Channel.CalcularInfijaAsync(request);
        }
        
        public System.Threading.Tasks.Task<_08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaResponse> CalcularInfijaAsync(_08___Calculadora_Web_Service.ServiceReference1.ArrayOfString elementos) {
            _08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaRequest inValue = new _08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaRequest();
            inValue.Body = new _08___Calculadora_Web_Service.ServiceReference1.CalcularInfijaRequestBody();
            inValue.Body.elementos = elementos;
            return ((_08___Calculadora_Web_Service.ServiceReference1.WebService1Soap)(this)).CalcularInfijaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaResponse _08___Calculadora_Web_Service.ServiceReference1.WebService1Soap.CalcularPostfija(_08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaRequest request) {
            return base.Channel.CalcularPostfija(request);
        }
        
        public string CalcularPostfija(_08___Calculadora_Web_Service.ServiceReference1.ArrayOfString elementos) {
            _08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaRequest inValue = new _08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaRequest();
            inValue.Body = new _08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaRequestBody();
            inValue.Body.elementos = elementos;
            _08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaResponse retVal = ((_08___Calculadora_Web_Service.ServiceReference1.WebService1Soap)(this)).CalcularPostfija(inValue);
            return retVal.Body.CalcularPostfijaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaResponse> _08___Calculadora_Web_Service.ServiceReference1.WebService1Soap.CalcularPostfijaAsync(_08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaRequest request) {
            return base.Channel.CalcularPostfijaAsync(request);
        }
        
        public System.Threading.Tasks.Task<_08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaResponse> CalcularPostfijaAsync(_08___Calculadora_Web_Service.ServiceReference1.ArrayOfString elementos) {
            _08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaRequest inValue = new _08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaRequest();
            inValue.Body = new _08___Calculadora_Web_Service.ServiceReference1.CalcularPostfijaRequestBody();
            inValue.Body.elementos = elementos;
            return ((_08___Calculadora_Web_Service.ServiceReference1.WebService1Soap)(this)).CalcularPostfijaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaResponse _08___Calculadora_Web_Service.ServiceReference1.WebService1Soap.CalcularPrefija(_08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaRequest request) {
            return base.Channel.CalcularPrefija(request);
        }
        
        public string CalcularPrefija(_08___Calculadora_Web_Service.ServiceReference1.ArrayOfString elementos) {
            _08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaRequest inValue = new _08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaRequest();
            inValue.Body = new _08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaRequestBody();
            inValue.Body.elementos = elementos;
            _08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaResponse retVal = ((_08___Calculadora_Web_Service.ServiceReference1.WebService1Soap)(this)).CalcularPrefija(inValue);
            return retVal.Body.CalcularPrefijaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaResponse> _08___Calculadora_Web_Service.ServiceReference1.WebService1Soap.CalcularPrefijaAsync(_08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaRequest request) {
            return base.Channel.CalcularPrefijaAsync(request);
        }
        
        public System.Threading.Tasks.Task<_08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaResponse> CalcularPrefijaAsync(_08___Calculadora_Web_Service.ServiceReference1.ArrayOfString elementos) {
            _08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaRequest inValue = new _08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaRequest();
            inValue.Body = new _08___Calculadora_Web_Service.ServiceReference1.CalcularPrefijaRequestBody();
            inValue.Body.elementos = elementos;
            return ((_08___Calculadora_Web_Service.ServiceReference1.WebService1Soap)(this)).CalcularPrefijaAsync(inValue);
        }
    }
}
